
import React, { useState } from 'react';
import { Search, Pill, Zap, Microscope, ChevronDown, FlaskConical, Settings, CheckCircle2 } from 'lucide-react';
import { 
  PREDEFINED_DRUGS, 
  PREDEFINED_PROTEINS,
  DESIGN_MOLECULE_TYPES,
  DESIGN_TARGET_SYSTEMS,
  DESIGN_MW_CLASS,
  DESIGN_HYDROPHOBICITY,
  DESIGN_CHARGE,
  DESIGN_FUNCTIONAL_GROUPS
} from '../constants';
import { AnalysisMode, CustomDrugParams } from '../types';

interface InputSectionProps {
  onAnalyze: (drug: string, protein: string, mode: AnalysisMode, customParams?: CustomDrugParams) => void;
  isLoading: boolean;
}

const InputSection: React.FC<InputSectionProps> = ({ onAnalyze, isLoading }) => {
  const [mode, setMode] = useState<AnalysisMode>('existing');

  // Existing Mode State
  const [drug, setDrug] = useState('');
  const [protein, setProtein] = useState('');
  const [selectedDrugPreset, setSelectedDrugPreset] = useState('');
  const [selectedProteinPreset, setSelectedProteinPreset] = useState('');

  // Custom Design Mode State
  const [customParams, setCustomParams] = useState<CustomDrugParams>({
    moleculeType: DESIGN_MOLECULE_TYPES[0].value,
    targetSystem: DESIGN_TARGET_SYSTEMS[0].value,
    molecularWeight: DESIGN_MW_CLASS[1].value,
    hydrophobicity: DESIGN_HYDROPHOBICITY[1].value,
    charge: DESIGN_CHARGE[0].value,
    functionalGroups: []
  });

  const handleExistingSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (drug && protein) {
      onAnalyze(drug, protein, 'existing');
    }
  };

  const handleCustomSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // In custom mode, 'drug' and 'protein' are generated by AI, so we pass empty strings or placeholders
    onAnalyze("Custom Drug", "Auto-Predict", 'custom', customParams);
  };

  const handleDrugPresetChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const val = e.target.value;
    setSelectedDrugPreset(val);
    if (val) setDrug(val);
  };

  const handleProteinPresetChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const val = e.target.value;
    setSelectedProteinPreset(val);
    if (val) setProtein(val);
  };

  const toggleFunctionalGroup = (group: string) => {
    setCustomParams(prev => {
      if (prev.functionalGroups.includes(group)) {
        return { ...prev, functionalGroups: prev.functionalGroups.filter(g => g !== group) };
      } else {
        return { ...prev, functionalGroups: [...prev.functionalGroups, group] };
      }
    });
  };

  return (
    <div className="bg-slate-800/50 border border-slate-700 rounded-2xl p-6 sm:p-8 shadow-xl backdrop-blur-sm">
      
      {/* Mode Tabs */}
      <div className="flex space-x-1 bg-slate-900/50 p-1 rounded-xl mb-8">
        <button
          onClick={() => setMode('existing')}
          className={`flex-1 flex items-center justify-center py-2.5 text-sm font-medium rounded-lg transition-all ${
            mode === 'existing' 
              ? 'bg-slate-700 text-white shadow-md' 
              : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'
          }`}
        >
          <Search className="w-4 h-4 mr-2" />
          기존 약물 분석
        </button>
        <button
          onClick={() => setMode('custom')}
          className={`flex-1 flex items-center justify-center py-2.5 text-sm font-medium rounded-lg transition-all ${
            mode === 'custom' 
              ? 'bg-science-600 text-white shadow-md' 
              : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'
          }`}
        >
          <FlaskConical className="w-4 h-4 mr-2" />
          신약 설계 및 타겟 예측
        </button>
      </div>

      {mode === 'existing' ? (
        // --- EXISTING DRUG MODE ---
        <form onSubmit={handleExistingSubmit} className="space-y-8 animate-fade-in">
          <h2 className="text-xl font-semibold text-white mb-6 flex items-center gap-2">
            <Microscope className="w-5 h-5 text-science-500" />
            분석 파라미터 설정
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Drug Input Section */}
            <div className="space-y-3">
              <label htmlFor="drug" className="block text-sm font-medium text-science-400 uppercase tracking-wide">
                1. 약물/물질 선택 (Ligand)
              </label>
              
              <div className="relative">
                 <select
                  value={selectedDrugPreset}
                  onChange={handleDrugPresetChange}
                  disabled={isLoading}
                  className="appearance-none block w-full pl-3 pr-10 py-2.5 bg-slate-900 border border-slate-700 rounded-lg text-slate-300 focus:outline-none focus:border-science-500 text-sm transition-colors cursor-pointer"
                >
                  <option value="" disabled>약물 또는 물질 선택...</option>
                  {PREDEFINED_DRUGS.map((group, groupIdx) => (
                    <optgroup key={groupIdx} label={group.category}>
                      {group.options.map((option, optIdx) => (
                        <option key={optIdx} value={option.value}>
                          {option.label}
                        </option>
                      ))}
                    </optgroup>
                  ))}
                </select>
                 <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-slate-500">
                  <ChevronDown className="h-4 w-4" />
                </div>
              </div>

              <div className="relative group">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <Pill className="h-5 w-5 text-slate-500 group-focus-within:text-science-500 transition-colors" />
                </div>
                <input
                  type="text"
                  id="drug"
                  className="block w-full pl-10 pr-3 py-3 bg-slate-900/50 border border-slate-700 rounded-xl text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-science-500 focus:border-transparent transition-all shadow-inner"
                  placeholder="약물 이름, 물질명 또는 SMILES 코드"
                  value={drug}
                  onChange={(e) => {
                    setDrug(e.target.value);
                    setSelectedDrugPreset('');
                  }}
                  disabled={isLoading}
                />
              </div>
            </div>

            {/* Protein Input Section */}
            <div className="space-y-3">
              <label htmlFor="protein" className="block text-sm font-medium text-dna-500 uppercase tracking-wide">
                2. 단백질 타겟 선택 (Target)
              </label>

               <div className="relative">
                 <select
                  value={selectedProteinPreset}
                  onChange={handleProteinPresetChange}
                  disabled={isLoading}
                  className="appearance-none block w-full pl-3 pr-10 py-2.5 bg-slate-900 border border-slate-700 rounded-lg text-slate-300 focus:outline-none focus:border-dna-500 text-sm transition-colors cursor-pointer"
                >
                  <option value="" disabled>단백질 타겟 선택...</option>
                  {PREDEFINED_PROTEINS.map((group, groupIdx) => (
                     <optgroup key={groupIdx} label={group.category}>
                      {group.options.map((option, optIdx) => (
                        <option key={optIdx} value={option.value}>
                          {option.label}
                        </option>
                      ))}
                    </optgroup>
                  ))}
                </select>
                <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-slate-500">
                  <ChevronDown className="h-4 w-4" />
                </div>
              </div>

              <div className="relative group">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <Zap className="h-5 w-5 text-slate-500 group-focus-within:text-dna-500 transition-colors" />
                </div>
                <input
                  type="text"
                  id="protein"
                  className="block w-full pl-10 pr-3 py-3 bg-slate-900/50 border border-slate-700 rounded-xl text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-dna-500 focus:border-transparent transition-all shadow-inner"
                  placeholder="단백질 이름 또는 PDB ID 입력"
                  value={protein}
                  onChange={(e) => {
                    setProtein(e.target.value);
                    setSelectedProteinPreset('');
                  }}
                  disabled={isLoading}
                />
              </div>
            </div>
          </div>

          <div className="flex justify-end pt-4 border-t border-slate-700/50">
            <button
              type="submit"
              disabled={isLoading || !drug || !protein}
              className={`
                flex items-center justify-center px-8 py-3 rounded-xl text-white font-medium shadow-lg transition-all transform hover:scale-[1.02] active:scale-95
                ${isLoading || !drug || !protein 
                  ? 'bg-slate-700 cursor-not-allowed text-slate-400' 
                  : 'bg-gradient-to-r from-science-600 to-dna-600 hover:from-science-500 hover:to-dna-500 shadow-science-900/50'}
              `}
            >
              {isLoading ? '분석 중...' : '구조 예측 실행'}
            </button>
          </div>
        </form>
      ) : (
        // --- CUSTOM DESIGN MODE ---
        <form onSubmit={handleCustomSubmit} className="space-y-6 animate-fade-in">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-xl font-semibold text-white flex items-center gap-2">
              <Settings className="w-5 h-5 text-science-500" />
              미지의 약물 설계 (Custom Drug Design)
            </h2>
            <span className="text-xs text-slate-400 bg-slate-900 px-3 py-1 rounded-full border border-slate-700">
              AI가 인체 내 최적 타겟을 자동 추천합니다
            </span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            
            {/* 1. Molecule Type */}
            <div className="space-y-2">
              <label className="text-sm font-medium text-slate-400">1. 분자 종류 (Molecule Type)</label>
              <select 
                className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-slate-200 focus:border-science-500 outline-none"
                value={customParams.moleculeType}
                onChange={e => setCustomParams({...customParams, moleculeType: e.target.value})}
              >
                {DESIGN_MOLECULE_TYPES.map(opt => <option key={opt.value} value={opt.value}>{opt.label}</option>)}
              </select>
            </div>

            {/* 2. Target System */}
            <div className="space-y-2">
              <label className="text-sm font-medium text-slate-400">2. 타겟 인체 시스템 (Target System)</label>
              <select 
                className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-slate-200 focus:border-science-500 outline-none"
                value={customParams.targetSystem}
                onChange={e => setCustomParams({...customParams, targetSystem: e.target.value})}
              >
                {DESIGN_TARGET_SYSTEMS.map(opt => <option key={opt.value} value={opt.value}>{opt.label}</option>)}
              </select>
            </div>

            {/* 3. Molecular Weight */}
            <div className="space-y-2">
              <label className="text-sm font-medium text-slate-400">3. 분자량 크기 (Molecular Weight)</label>
              <select 
                className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-slate-200 focus:border-science-500 outline-none"
                value={customParams.molecularWeight}
                onChange={e => setCustomParams({...customParams, molecularWeight: e.target.value})}
              >
                {DESIGN_MW_CLASS.map(opt => <option key={opt.value} value={opt.value}>{opt.label}</option>)}
              </select>
            </div>

            {/* 4. Hydrophobicity */}
            <div className="space-y-2">
              <label className="text-sm font-medium text-slate-400">4. 물/지방 친화도 (LogP)</label>
              <select 
                className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-slate-200 focus:border-science-500 outline-none"
                value={customParams.hydrophobicity}
                onChange={e => setCustomParams({...customParams, hydrophobicity: e.target.value})}
              >
                {DESIGN_HYDROPHOBICITY.map(opt => <option key={opt.value} value={opt.value}>{opt.label}</option>)}
              </select>
            </div>

            {/* 5. Charge */}
             <div className="space-y-2">
              <label className="text-sm font-medium text-slate-400">5. 전하 (Charge at pH 7.4)</label>
              <select 
                className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-slate-200 focus:border-science-500 outline-none"
                value={customParams.charge}
                onChange={e => setCustomParams({...customParams, charge: e.target.value})}
              >
                {DESIGN_CHARGE.map(opt => <option key={opt.value} value={opt.value}>{opt.label}</option>)}
              </select>
            </div>
          </div>

          {/* 6. Functional Groups (Multi-select) */}
          <div className="space-y-3 pt-4 border-t border-slate-700/50">
            <label className="text-sm font-medium text-slate-400 block">6. 주요 작용기 포함 (Functional Groups)</label>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              {DESIGN_FUNCTIONAL_GROUPS.map((group) => {
                const isSelected = customParams.functionalGroups.includes(group);
                return (
                  <button
                    key={group}
                    type="button"
                    onClick={() => toggleFunctionalGroup(group)}
                    className={`
                      px-3 py-2 rounded-lg text-xs font-medium text-left transition-all border
                      ${isSelected 
                        ? 'bg-science-900/50 border-science-500 text-science-200' 
                        : 'bg-slate-900 border-slate-700 text-slate-400 hover:border-slate-500'}
                    `}
                  >
                    <div className="flex items-center justify-between">
                      {group.split('(')[0]}
                      {isSelected && <CheckCircle2 className="w-3 h-3 text-science-500" />}
                    </div>
                  </button>
                );
              })}
            </div>
          </div>

          <div className="flex justify-end pt-4 border-t border-slate-700/50">
            <button
              type="submit"
              disabled={isLoading}
              className={`
                flex items-center justify-center px-8 py-3 rounded-xl text-white font-medium shadow-lg transition-all transform hover:scale-[1.02] active:scale-95
                bg-gradient-to-r from-science-600 to-indigo-600 hover:from-science-500 hover:to-indigo-500 shadow-indigo-900/50
              `}
            >
              {isLoading ? (
                <>
                  <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  가상 약물 분석 및 타겟 예측 중...
                </>
              ) : (
                <>
                  <FlaskConical className="w-5 h-5 mr-2" />
                  타겟 예측 및 결합 분석 시작
                </>
              )}
            </button>
          </div>
        </form>
      )}
    </div>
  );
};

export default InputSection;
